
secrets:
  grafana_admin_password:
    file: ./secrets/GF_PASSWORD.txt


services:
  prometheus:
    # Description: This container runs Prometheus, 
    # an open-source monitoring and alerting toolkit.
    # It collects and stores metrics from configured targets at specified intervals,
    # evaluates rule expressions, displays results, and can trigger alerts if certain conditions are observed.
    image: prom/prometheus:latest
    container_name: service_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: service_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
      GF_INSTALL_PLUGINS: "grafana-piechart-panel"
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - monitoring

  loki:
    # Loki 是一個由 Grafana Labs 開發的水平可擴展的日誌聚合系統，專為高效存儲和查詢大量日誌數據而設計。
    # 它使用類似 Prometheus 的標籤系統來組織和索引日誌，使得在大規模環境中管理和分析日誌變得更加高效和靈活。
    image: grafana/loki:latest
    container_name: service_loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki/local-config.yaml
      - ./loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - monitoring

  tempo:
    # Tempo 是 Grafana Labs 開發的分佈式追蹤後端，專為高效存儲和查詢大量追蹤數據而設計。
    image: grafana/tempo:latest
    container_name: service_tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - ./tempo_data:/var/tempo
    command: -config.file=/etc/tempo.yml
    restart: unless-stopped
    networks:
      - monitoring

  mimir:
    # Mimir 是 Grafana Labs 開發的分佈式指標後端，專為高效存儲和查詢大量指標數據而設計。
    image: grafana/mimir:latest
    container_name: service_mimir
    ports:
      - "9009:9009"
    volumes:
      - ./mimir.yml:/etc/mimir/mimir.yml
      - ./mimir_data:/mimir
    command: -config.file=/etc/mimir/mimir.yml
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  tempo_data:
  mimir_data:

networks:
  monitoring:
