# archive_mode=on 啟用 PostgreSQL 的 WAL（Write-Ahead Logging）檔案的歸檔功能。這是 pgBackRest 正常運作的必要條件，因為 pgBackRest 依賴於 WAL 檔案來進行增量備份和恢復。
archive_mode=on
# 多久進行一次 WAL 傳輸，單位為秒。這裡設定為 28800 秒（8 小時），意味著 pgBackRest 將每 8 小時嘗試將 WAL 檔案傳輸到備份存儲位置。
# 不一定要等到檔案大小到達 16MB 才進行傳輸。
archive_timeout=28800

# 歸檔的指令
archive_command='/usr/local/bin/pgbackrest-secret.sh --stanza=main archive-push %p #pgbackrest'
# wal_level: 設定為 replica，這是 pgBackRest 進行增量備份和流式備份所需的最低 wal_level。這個設定確保 PostgreSQL 會生成足夠的 WAL 資訊，以便 pgBackRest 能夠正確地捕捉和備份數據變更。
# replica代表
wal_level=replica
