[pg-server]
description = "PostgreSQL Streaming Backup"

# 連線資訊 (使用 Docker 服務名稱，user、password 和 dbname 根據實際情況修改)
conninfo = host=service_postgres_barman password=peteradmin user=peter dbname=mydb
streaming_conninfo = host=service_postgres_barman password=peteradmin user=peter dbname=mydb

# 設定為 Streaming 模式
backup_method = postgres
streaming_archiver = on
slot_name = barman_slot 

# 備份存放路徑 (一般的barman 的 home 目錄)
backup_directory = /var/lib/barman/pg-server
